highlighter: rouge
domain: zhaojun-nlpr.github.io
url: https://zhaojun-nlpr.github.io
permalink: /blog/:year/:month/:day/:title/
environment: prod
plugins:
  # - jekyll-scholar
  - jekyll-sitemap
  - jekyll-feed
